name: microcosmos
synopsis: A very small content management system.
description: A very small content management system.

maintainer: Alex Dixon <alex@dixonary.co.uk>
license: MIT

verbatim:
  cabal-version: 2.2

category: web

dependencies:
- base >=4.10 && <5
- text
- bytestring
- text-icu
- witch
- extra
- sqlite-simple
- string-interpolate
- directory
- filepath
- fsnotify
- process
- file-embed
- wai
- warp
- wai-middleware-static
- http-types
- attoparsec
- parser-combinators
- terminal-progress-bar

default-extensions:
- DataKinds
- DuplicateRecordFields
- MultiParamTypeClasses     
- ScopedTypeVariables       
- TemplateHaskell           
- TypeApplications          
- TypeFamilies              
- GeneralizedNewtypeDeriving
- LambdaCase
- BlockArguments
- TupleSections
- MultiWayIf
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- ConstraintKinds
- QuantifiedConstraints
- FlexibleContexts
- RecordWildCards
- NondecreasingIndentation
- DeriveGeneric
- StandaloneDeriving

executables:
  mc:
    main: Main.hs
    source-dirs: app
    ghc-options: [ -split-sections  ]